# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 21:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriStatePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(choices=[('nj', 'New Jersey'), ('ny', 'New York'), ('ct', 'Connecticut')], max_length=20)),
                ('zip', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only numeric characters are allowed.')])),
            ],
        ),
    ]
